//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Button_Check {
            get {
                return ResourceManager.GetString("Button_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any duplicates?.
        /// </summary>
        public static string Button_Duplicates {
            get {
                return ResourceManager.GetString("Button_Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data.
        /// </summary>
        public static string Button_GetData {
            get {
                return ResourceManager.GetString("Button_GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results gotten.
        /// </summary>
        public static string Label_Done {
            get {
                return ResourceManager.GetString("Label_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting year.
        /// </summary>
        public static string Label_Year {
            get {
                return ResourceManager.GetString("Label_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombian Baloto Results.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}Type: {1}Winner: {2}.
        /// </summary>
        public static string String_CheckResult {
            get {
                return ResourceManager.GetString("String_CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal duplicates: {0}Second chance duplicates: {1}Total duplicates: {2}.
        /// </summary>
        public static string String_DuplicatesResult {
            get {
                return ResourceManager.GetString("String_DuplicatesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number has not been a result.
        /// </summary>
        public static string String_IsNotResult {
            get {
                return ResourceManager.GetString("String_IsNotResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number WAS a result already.
        /// </summary>
        public static string String_IsResult {
            get {
                return ResourceManager.GetString("String_IsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string String_No {
            get {
                return ResourceManager.GetString("String_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string String_TypeNormal {
            get {
                return ResourceManager.GetString("String_TypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second chance.
        /// </summary>
        public static string String_TypeSecondChance {
            get {
                return ResourceManager.GetString("String_TypeSecondChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string String_Yes {
            get {
                return ResourceManager.GetString("String_Yes", resourceCulture);
            }
        }
    }
}
